site_name: TaskFlow Infrastructure
site_description: Terraform infrastructure for the TaskFlow platform

repo_url: https://github.com/OnyiGlobal2025/taskflow-infra
edit_uri: edit/main/docs/

nav:
  - Home: index.md
  - Architecture: architecture.md

plugins:
  - techdocs-core

